"""init

Revision ID: da87ac5e4dac
Revises: 
Create Date: 2025-11-30 13:37:36.250845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da87ac5e4dac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_author_id'), 'authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_authors_full_name'), 'authors', ['full_name'], unique=True)
    op.create_table('libraries',
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_index(op.f('ix_libraries_library_id'), 'libraries', ['library_id'], unique=False)
    op.create_index(op.f('ix_libraries_name'), 'libraries', ['name'], unique=True)
    op.create_table('readers',
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('reg_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.PrimaryKeyConstraint('reader_id')
    )
    op.create_index(op.f('ix_readers_full_name'), 'readers', ['full_name'], unique=False)
    op.create_index(op.f('ix_readers_phone'), 'readers', ['phone'], unique=True)
    op.create_index(op.f('ix_readers_reader_id'), 'readers', ['reader_id'], unique=False)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_index(op.f('ix_topics_topic_id'), 'topics', ['topic_id'], unique=False)
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('publish_place', sa.String(length=100), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('price >= 0', name='check_price'),
    sa.CheckConstraint('publish_year BETWEEN 1500 AND EXTRACT(YEAR FROM CURRENT_DATE)', name='check_publish_year'),
    sa.CheckConstraint('quantity >= 0', name='check_quantity'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.library_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('deposit >= 0', name='check_deposit'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.library_id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.reader_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_topics_topic_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_readers_reader_id'), table_name='readers')
    op.drop_index(op.f('ix_readers_phone'), table_name='readers')
    op.drop_index(op.f('ix_readers_full_name'), table_name='readers')
    op.drop_table('readers')
    op.drop_index(op.f('ix_libraries_name'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_library_id'), table_name='libraries')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_authors_full_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_author_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
